import { Injectable } from '@angular/core';

@Injectable()
export class ProductService {
  getProductsData() {
    return [
      {
        id: '1000',
        code: 'f230fh0g3',
        name: 'Bamboo Watch',
        description: 'Product Description',
        image: 'Admin',
        role: 'admin',
        price: 65,
        email: 'admin1@example.com',
        category: 'CAS Scales',
        quantity: 24,
        inventoryStatus: 'Active',
        location: 5,
      },
      {
        id: '1001',
        code: 'nvklal433',
        name: 'Black Watch',
        description: 'Product Description',
        image: 'black-watch.jpg',
        role: 'shipper',
        price: 72,
        email: 'shipper1@example.com',
        category: 'Mettler Toledo',
        quantity: 61,
        inventoryStatus: 'InActive',
        location: 4,
      },
      {
        id: '1002',
        code: 'zz21cz3c1',
        name: 'Blue Band',
        description: 'Product Description',
        image: 'blue-band.jpg',
        role: 'admin',
        price: 79,
        email: 'admin2@example.com',
        category: 'Adam Equipment',
        quantity: 2,
        inventoryStatus: 'InActive',
        location: 3,
      },
      {
        id: '1003',
        code: '244wgerg2',
        name: 'Blue T-Shirt',
        description: 'Product Description',
        image: 'blue-t-shirt.jpg',
        role: 'shipper',
        price: 29,
        email: 'shipper2@example.com',
        category: 'A&D Weighing',
        quantity: 25,
        inventoryStatus: 'Active',
        location: 5,
      },
      {
        id: '1004',
        code: 'h456wer53',
        name: 'Bracelet',
        description: 'Product Description',
        image: 'bracelet.jpg',
        role: 'admin',
        price: 15,
        email: 'admin3@example.com',
        category: 'CAS Scales',
        quantity: 73,
        inventoryStatus: 'Active',
        location: 4,
      },
      {
        id: '1005',
        code: 'av2231fwg',
        name: 'Brown Purse',
        description: 'Product Description',
        image: 'brown-purse.jpg',
        role: 'shipper',
        price: 120,
        email: 'shipper3@example.com',
        category: 'CAS Scales',
        quantity: 0,
        inventoryStatus: 'InActive',
        location: 4,
      },
      {
        id: '1006',
        code: 'bib36pfvm',
        name: 'Chakra Bracelet',
        description: 'Product Description',
        image: 'chakra-bracelet.jpg',
        role: 'admin',
        price: 32,
        email: 'admin4@example.com',
        category: 'CAS Scales',
        quantity: 5,
        inventoryStatus: 'InActive',
        location: 3,
      },
      {
        id: '1007',
        code: 'mbvjkgip5',
        name: 'Galaxy Earrings',
        description: 'Product Description',
        image: 'galaxy-earrings.jpg',
        role: 'shipper',
        price: 34,
        email: 'shipper4@example.com',
        category: 'CAS Scales',
        quantity: 23,
        inventoryStatus: 'Active',
        location: 5,
      },
      {
        id: '1008',
        code: 'vbb124btr',
        name: 'Game Controller',
        description: 'Product Description',
        image: 'game-controller.jpg',
        role: 'admin',
        price: 99,
        email: 'admin5@example.com',
        category: 'Citizen Scales',
        quantity: 2,
        inventoryStatus: 'InActive',
        location: 4,
      },
      {
        id: '1009',
        code: 'cm230f032',
        name: 'Gaming Set',
        description: 'Product Description',
        image: 'gaming-set.jpg',
        role: 'shipper',
        price: 299,
        email: 'shipper5@example.com',
        category: 'Citizen Scales',
        quantity: 63,
        inventoryStatus: 'Active',
        location: 3,
      },
      {
        id: '1010',
        code: 'plb34234v',
        name: 'Gold Phone Case',
        description: 'Product Description',
        image: 'gold-phone-case.jpg',
        role: 'admin',
        price: 24,
        email: 'admin6@example.com',
        category: 'CAS Scales',
        quantity: 0,
        inventoryStatus: 'InActive',
        location: 4,
      },
      {
        id: '1011',
        code: '4920nnc2d',
        name: 'Green Earbuds',
        description: 'Product Description',
        image: 'green-earbuds.jpg',
        role: 'shipper',
        price: 89,
        email: 'shipper6@example.com',
        category: 'Citizen Scales',
        quantity: 23,
        inventoryStatus: 'Active',
        location: 4,
      },
      {
        id: '1012',
        code: '250vm23cc',
        name: 'Green T-Shirt',
        description: 'Product Description',
        image: 'green-t-shirt.jpg',
        role: 'admin',
        price: 49,
        email: 'admin7@example.com',
        category: 'A&D Weighing',
        quantity: 74,
        inventoryStatus: 'Active',
        location: 5,
      },
      {
        id: '1013',
        code: 'fldsmn31b',
        name: 'Grey T-Shirt',
        description: 'Product Description',
        image: 'grey-t-shirt.jpg',
        role: 'shipper',
        price: 48,
        email: 'shipper7@example.com',
        category: 'A&D Weighing',
        quantity: 0,
        inventoryStatus: 'InActive',
        location: 3,
      },
      {
        id: '1014',
        code: 'waas1x2as',
        name: 'Headphones',
        description: 'Product Description',
        image: 'headphones.jpg',
        role: 'admin',
        price: 175,
        email: 'admin8@example.com',
        category: 'Citizen Scales',
        quantity: 8,
        inventoryStatus: 'InActive',
        location: 5,
      },
      {
        id: '1015',
        code: 'vb34btbg5',
        name: 'Light Green T-Shirt',
        description: 'Product Description',
        image: 'light-green-t-shirt.jpg',
        role: 'shipper',
        price: 49,
        email: 'shipper8@example.com',
        category: 'A&D Weighing',
        quantity: 34,
        inventoryStatus: 'Active',
        location: 4,
      },
      // ... continue with the same alternating role and unique dummy email format
    ];
  }

  getProductsWithOrdersData() {
    return [
      {
        id: '1000',
        code: 'f230fh0g3',
        name: 'Bamboo Watch',
        description: 'Product Description',
        image: 'bamboo-watch.jpg',
        price: 65,
        category: 'CAS Scales',
        quantity: 24,
        inventoryStatus: 'Active',
        location: 5,
        orders: [
          {
            id: '1000-0',
            productCode: 'f230fh0g3',
            date: '2020-09-13',
            amount: 65,
            quantity: 1,
            customer: 'David James',
            status: 'PENDING',
          },
          {
            id: '1000-1',
            productCode: 'f230fh0g3',
            date: '2020-05-14',
            amount: 130,
            quantity: 2,
            customer: 'Leon Rodrigues',
            status: 'DELIVERED',
          },
          {
            id: '1000-2',
            productCode: 'f230fh0g3',
            date: '2019-01-04',
            amount: 65,
            quantity: 1,
            customer: 'Juan Alejandro',
            status: 'RETURNED',
          },
          {
            id: '1000-3',
            productCode: 'f230fh0g3',
            date: '2020-09-13',
            amount: 195,
            quantity: 3,
            customer: 'Claire Morrow',
            status: 'CANCELLED',
          },
        ],
      },
      {
        id: '1001',
        code: 'nvklal433',
        name: 'Black Watch',
        description: 'Product Description',
        image: 'black-watch.jpg',
        price: 72,
        category: 'CAS Scales',
        quantity: 61,
        inventoryStatus: 'Active',
        location: 4,
        orders: [
          {
            id: '1001-0',
            productCode: 'nvklal433',
            date: '2020-05-14',
            amount: 72,
            quantity: 1,
            customer: 'Maisha Jefferson',
            status: 'DELIVERED',
          },
          {
            id: '1001-1',
            productCode: 'nvklal433',
            date: '2020-02-28',
            amount: 144,
            quantity: 2,
            customer: 'Octavia Murillo',
            status: 'PENDING',
          },
        ],
      },
      {
        id: '1002',
        code: 'zz21cz3c1',
        name: 'Blue Band',
        description: 'Product Description',
        image: 'blue-band.jpg',
        price: 79,
        category: 'Adam Equipment',
        quantity: 2,
        inventoryStatus: 'InActive',
        location: 3,
        orders: [
          {
            id: '1002-0',
            productCode: 'zz21cz3c1',
            date: '2020-07-05',
            amount: 79,
            quantity: 1,
            customer: 'Stacey Leja',
            status: 'DELIVERED',
          },
          {
            id: '1002-1',
            productCode: 'zz21cz3c1',
            date: '2020-02-06',
            amount: 79,
            quantity: 1,
            customer: 'Ashley Wickens',
            status: 'DELIVERED',
          },
        ],
      },
      {
        id: '1003',
        code: '244wgerg2',
        name: 'Blue T-Shirt',
        description: 'Product Description',
        image: 'blue-t-shirt.jpg',
        price: 29,
        category: 'A&D Weighing',
        quantity: 25,
        inventoryStatus: 'Active',
        location: 5,
        orders: [],
      },
      {
        id: '1004',
        code: 'h456wer53',
        name: 'Bracelet',
        description: 'Product Description',
        image: 'bracelet.jpg',
        price: 15,
        category: 'CAS Scales',
        quantity: 73,
        inventoryStatus: 'Active',
        location: 4,
        orders: [
          {
            id: '1004-0',
            productCode: 'h456wer53',
            date: '2020-09-05',
            amount: 60,
            quantity: 4,
            customer: 'Mayumi Misaki',
            status: 'PENDING',
          },
          {
            id: '1004-1',
            productCode: 'h456wer53',
            date: '2019-04-16',
            amount: 2,
            quantity: 30,
            customer: 'Francesco Salvatore',
            status: 'DELIVERED',
          },
        ],
      },
      {
        id: '1005',
        code: 'av2231fwg',
        name: 'Brown Purse',
        description: 'Product Description',
        image: 'brown-purse.jpg',
        price: 120,
        category: 'CAS Scales',
        quantity: 0,
        inventoryStatus: 'InActive',
        location: 4,
        orders: [
          {
            id: '1005-0',
            productCode: 'av2231fwg',
            date: '2020-01-25',
            amount: 120,
            quantity: 1,
            customer: 'Isabel Sinclair',
            status: 'RETURNED',
          },
          {
            id: '1005-1',
            productCode: 'av2231fwg',
            date: '2019-03-12',
            amount: 240,
            quantity: 2,
            customer: 'Lionel Clifford',
            status: 'DELIVERED',
          },
          {
            id: '1005-2',
            productCode: 'av2231fwg',
            date: '2019-05-05',
            amount: 120,
            quantity: 1,
            customer: 'Cody Chavez',
            status: 'DELIVERED',
          },
        ],
      },
      {
        id: '1006',
        code: 'bib36pfvm',
        name: 'Chakra Bracelet',
        description: 'Product Description',
        image: 'chakra-bracelet.jpg',
        price: 32,
        category: 'CAS Scales',
        quantity: 5,
        inventoryStatus: 'InActive',
        location: 3,
        orders: [
          {
            id: '1006-0',
            productCode: 'bib36pfvm',
            date: '2020-02-24',
            amount: 32,
            quantity: 1,
            customer: 'Arvin Darci',
            status: 'DELIVERED',
          },
          {
            id: '1006-1',
            productCode: 'bib36pfvm',
            date: '2020-01-14',
            amount: 64,
            quantity: 2,
            customer: 'Izzy Jones',
            status: 'PENDING',
          },
        ],
      },
      {
        id: '1007',
        code: 'mbvjkgip5',
        name: 'Galaxy Earrings',
        description: 'Product Description',
        image: 'galaxy-earrings.jpg',
        price: 34,
        category: 'CAS Scales',
        quantity: 23,
        inventoryStatus: 'Active',
        location: 5,
        orders: [
          {
            id: '1007-0',
            productCode: 'mbvjkgip5',
            date: '2020-06-19',
            amount: 34,
            quantity: 1,
            customer: 'Jennifer Smith',
            status: 'DELIVERED',
          },
        ],
      },
    ];
  }

  getProductsMini() {
    return Promise.resolve(this.getProductsData().slice(0, 5));
  }

  getProductsSmall() {
    return Promise.resolve(this.getProductsData().slice(0, 10));
  }

  getProducts() {
    return Promise.resolve(this.getProductsData());
  }

  getProductsWithOrdersSmall() {
    return Promise.resolve(this.getProductsWithOrdersData().slice(0, 10));
  }

  getProductsWithOrders() {
    return Promise.resolve(this.getProductsWithOrdersData());
  }
}
